version: '2'

services:

  zookeeper:
    image: confluent/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
      - "2888"
      - "3888"

  kafka:
    image: confluent/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      KAFKA_BROKER_ID: 0
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.253
      KAFKA_PORT: 9092
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
    depends_on:
      - zookeeper

  cassandra:
    image: cassandra:3.7
    container_name: cassandra
    ports:
      - "7199:7199"
      - "9042:9042"
      - "9160:9160"
      - "7001:7001"

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"